### ISSUE TITLE
Does not work for charts with image tags that default to Chart.AppVersion

### ISSUE THREAD

**Issue by petewall** [vmware-tanzu/asset-relocation-tool-for-kubernetes#204]
I'm seeing more and more Helm charts that leave the `tag` field empty in favor of defaulting to the AppVersion field of the chart.

A few examples:
* [Grafana Agent](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent)
```yaml
image:
  # -- Grafana Agent image registry (defaults to docker.io)
  registry: "docker.io"
  # -- Grafana Agent image repository.
  repository: grafana/agent
  # -- (string) Grafana Agent image tag. When empty, the Chart's appVersion is
  # used.
  tag: null
```
* [Kube State Metrics](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics)
* [Node Exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter)

When I run relok8s with the following hints file (I'm using Grafana Agent as a subchart):
```yaml
---
# - "{{ .grafana-agent.image.registry }}/{{ .grafana-agent.image.repository }}:{{ .grafana-agent.image.tag }}"
```

I get this result:
```bash
% relok8s chart move -ihints.yaml --registry registry.exampke.com mychart.tgz
Chart provided
Computing relocation...

Error: failed to pull original images: failed to parse image reference: could not parse reference: docker.io/grafana/agent:<no value>
```
