### ISSUE TITLE
De-duplicate values file rewrites

### ISSUE THREAD

**Issue by petewall** [vmware-tanzu/asset-relocation-tool-for-kubernetes#75]
If a chart contains a global image registry value, we could possibly update that value many times, resulting in a strange output:

values.yaml
```
global:
  imageRegistry: docker.io

image:
  repository: bitnami/wordpress
  tag: 5.7.2-debian-10-r0

metrics:
  repository: pwall/apache-exporter
  tag:  0.8.0-debian-10-r378
```

running `relok8s chart move ... --registry harbor-repo.vmware.com` will result in:

```
Computing relocation...
...
Changes to be applied to wordpress/values.yaml:
  .global.imageRegistry: harbor-repo.vmware.com
  .global.imageRegistry: harbor-repo.vmware.com
```

This is confusing and could lead to uncertainty.
